### PR TITLE
Canvas

### PR DESCRIPTION
**Pull request by claban3**
This PR introduces a new wobbly figure animation, refactors and extends the p5 sketch code, and corrects some mobile incompatible button designs which were broken in the last PR. Please double check that this doesn't explode before we merge.

### CODE REVIEW

**Comment by aposp** [comment]
Added a force to make the swarm follow the location of the user's mouse. I just copied the way that shapes exert forces on each other, so there may be an argument to try a different method if we think it makes sense.

**Review by rmarco3e8 — COMMENTED** [review]
Looks great. Surprised that the wobbly swarm has no lag, it looks really cool. The wall padding should help with shapes moving off screen.

**Review by aposp — APPROVED** [review]
LGTM

**Comment by aposp** [comment]
ah thanks for that cory, i tried using the library but messed something up so i just skipped it. looks good

**Pull request merged**
